// <auto-generated />
namespace Nothi.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tokencreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tokencreate));
        
        string IMigrationMetadata.Id
        {
            get { return "202011102114543_tokencreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
